extract_conditions_task:
  description: |
    Thoroughly analyze the PDF document and extract ALL policy compliance conditions and requirements.
    Ensure completeness by reviewing each section of the document.
    Format the output as a structured list with condition ID, description, and reference (page/section).
  expected_output: A comprehensive, structured list of all policy compliance conditions with unique IDs, descriptions, and source references.
  agent: policy_analyzer

identify_risks_task:
  description: |
    For each extracted compliance condition, identify and analyze potential risks of non-compliance.
    Assess the likelihood and potential impact of each risk.
    Format the output as a structured list with risk ID, related condition ID, risk description, likelihood, and impact.
  expected_output: A detailed risk register mapping risks to compliance conditions with assessment of likelihood and impact.
  agent: risk_assessor
  context:
    - extract_conditions_task

design_controls_task:
  description: |
    For each identified risk, design appropriate controls to mitigate the risk and ensure compliance.
    Specify whether each control is preventive, detective, or corrective.
    Format the output as a structured list with control ID, related risk ID, control description, control type, and implementation considerations.
  expected_output: A comprehensive control framework with specific controls mapped to each identified risk.
  agent: control_designer
  context:
    - identify_risks_task

develop_tests_task:
  description: |
    For each control, develop detailed test procedures to verify implementation and effectiveness.
    Include specific steps, expected results, and evidence requirements for each test.
    Format the output as a structured audit program with test ID, related control ID, test objective, detailed test steps, and evidence requirements.
  expected_output: A detailed audit program with specific test procedures for each control to verify compliance with policy requirements.
  agent: audit_planner
  context:
    - design_controls_task

generate_report_task:
  description: |
    Compile all findings into a comprehensive report that includes:
    1. Executive summary of the policy analysis
    2. Complete listing of all compliance conditions
    3. Risk assessment results
    4. Control framework
    5. Audit test procedures
    6. Traceability matrix showing relationships between conditions, risks, controls, and tests
    Format the report in a professional, well-structured manner suitable for executive review.
  expected_output: A comprehensive compliance analysis report with all components and a traceability matrix.
  agent: policy_analyzer
  context:
    - extract_conditions_task
    - identify_risks_task
    - design_controls_task
    - develop_tests_task