extract_conditions_task:
  description: |
    Thoroughly analyze ALL preprocessed PDF chunks and extract ALL policy requirements.
    Search for keywords like 'shall', 'should', 'must', 'required', 'obligated' and other modal verbs to extract ALL requirements.
    Ensure COMPLETE coverage by reviewing EVERY document chunk.
    Format the output as a structured list with condition ID, description, and reference (document name, page/section).
    Include the source document name in each reference.
  expected_output: A comprehensive, structured list of all policy compliance conditions with unique IDs, descriptions, and source references including document names.
  agent: policy_analyzer

identify_risks_task:
  description: |
    For each extracted compliance condition, identify and analyze potential risks of non-compliance.
    Assess the likelihood and potential impact of each risk.
    Format the output as a structured list with risk ID, related condition ID, risk description, likelihood, and impact.
    Include references to the source document and page for each risk.
  expected_output: A detailed risk register mapping risks to compliance conditions with assessment of likelihood and impact and source references.
  agent: risk_assessor
  context:
    - extract_conditions_task

design_controls_task:
  description: |
    For each identified risk, design appropriate controls to mitigate the risk and ensure compliance.
    Specify whether each control is preventive, detective, or corrective.
    Format the output as a structured list with control ID, related risk ID, control description, control type, and implementation considerations.
    Include references to the original policy condition's document source and page.
  expected_output: A comprehensive control framework with specific controls mapped to each identified risk and traceability to source documents.
  agent: control_designer
  context:
    - identify_risks_task

develop_tests_task:
  description: |
    For each control, develop detailed test procedures to verify implementation and effectiveness.
    Include specific steps, expected results, and evidence requirements for each test.
    Format the output as a structured audit program with test ID, related control ID, test objective, detailed test steps, and evidence requirements.
    Maintain traceability to the original source documents by including references to document names and page numbers.
  expected_output: A detailed audit program with specific test procedures for each control to verify compliance with policy requirements with source traceability.
  agent: audit_planner
  context:
    - design_controls_task

generate_report_task:
  description: |
    Compile all findings into a comprehensive report that includes:
    1. Executive summary of the policy analysis
    2. Complete listing of all compliance conditions with document sources
    3. Risk assessment results
    4. Control framework
    5. Audit test procedures
    6. Traceability matrix showing relationships between conditions, risks, controls, and tests, including document sources
    Format the report in a professional, well-structured manner suitable for executive review.
    Ensure full traceability to source documents by including document names and page numbers in all references.
  expected_output: A comprehensive compliance analysis report with all components and a traceability matrix that includes source document references.
  agent: policy_analyzer
  context:
    - extract_conditions_task
    - identify_risks_task
    - design_controls_task
    - develop_tests_task